# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:15
from __future__ import unicode_literals

import chatbot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('text', models.TextField(default='\U0001f916 Whoops this message is empty.')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=chatbot.models.gen_id, max_length=36, primary_key=True, serialize=False)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roster.Person')),
            ],
        ),
    ]
