# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('val', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Session')),
            ],
        ),
        migrations.RemoveField(
            model_name='context',
            name='session',
        ),
        migrations.DeleteModel(
            name='Context',
        ),
    ]
