# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_session_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='finished',
            field=models.BooleanField(default=True),
        ),
    ]
