# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20160831_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default='\U0001f916 Whoops this message is empty.', max_length=160),
        ),
    ]
