# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20160903_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='person',
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='SessionData',
        ),
    ]
