# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:48
from __future__ import unicode_literals

import chatbot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_remove_person_short_messages'),
        ('chatbot', '0008_auto_20160903_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv_id', models.CharField(default=chatbot.models.gen_id, max_length=36)),
                ('finished', models.BooleanField(default=False)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roster.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('val', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Session')),
            ],
        ),
    ]
