# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_session_sessiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='body',
        ),
    ]
