# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 04:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_auto_20160904_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tag',
            field=models.CharField(max_length=100, validators=(django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric and underscores are allowed.'),)),
        ),
    ]
