# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='banner_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='classification',
            field=models.CharField(blank=True, choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior'), ('masters', 'Masters'), ('doctoral', 'Doctoral'), ('not_student', 'Not a Student')], max_length=15),
        ),
    ]
