# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_auto_20160831_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='banner_id',
        ),
    ]
