# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_person_short_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='short_messages',
        ),
    ]
