# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_remove_person_short_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_consent',
            field=models.BooleanField(default=False),
        ),
    ]
