# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_auto_20160928_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo_consent',
            field=models.BooleanField(default=False),
        ),
    ]
