# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_auto_20160928_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='person_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
