# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_auto_20161004_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_filled',
            new_name='self_filled',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_updated',
            new_name='self_updated',
        ),
    ]
