# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 07:55
from __future__ import unicode_literals

import cal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20160902_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cal.Event')),
                ('short_code', models.CharField(default=cal.models.gen_checkin_code, max_length=4)),
                ('rsvp_enabled', models.BooleanField(default=False)),
                ('rsvp_limit', models.IntegerField(blank=True, null=True)),
                ('rsvp_message', models.CharField(blank=True, max_length=160)),
                ('checkin_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Event settings',
                'verbose_name': 'Event setting',
            },
        ),
        migrations.RemoveField(
            model_name='checkinsettings',
            name='event',
        ),
        migrations.RemoveField(
            model_name='rsvpsettings',
            name='event',
        ),
        migrations.DeleteModel(
            name='CheckinSettings',
        ),
        migrations.DeleteModel(
            name='RSVPSettings',
        ),
    ]
