# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20160902_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='checkin',
            order_with_respect_to='event',
        ),
        migrations.AlterOrderWithRespectTo(
            name='eventsettings',
            order_with_respect_to='event',
        ),
        migrations.AlterOrderWithRespectTo(
            name='rsvp',
            order_with_respect_to='event',
        ),
    ]
