# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20160903_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='eventsettings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ('-created_at',), 'verbose_name': 'RSVP', 'verbose_name_plural': "RSVP's"},
        ),
        migrations.AddField(
            model_name='checkin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 3, 6, 45, 7, 641345, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 3, 6, 45, 16, 696551, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='checkin',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='eventsettings',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='rsvp',
            order_with_respect_to=None,
        ),
    ]
