# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20160903_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='person',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='roster.Person'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='event',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='cal.Event'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='person',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='roster.Person'),
        ),
    ]
