# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20160903_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsettings',
            name='rsvp_message',
        ),
    ]
