# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_session_sessiondata'),
        ('cal', '0009_remove_eventsettings_rsvp_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='rsvp_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Message'),
        ),
    ]
