# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_auto_20160904_0342'),
        ('cal', '0011_auto_20160904_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='checkin_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_message', to='chatbot.Message'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='rsvp_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvp_message', to='chatbot.Message'),
        ),
    ]
