# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_auto_20160904_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='roster.Person'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='roster.Person'),
        ),
    ]
