# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_remove_person_short_messages'),
        ('cal', '0014_auto_20160904_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Person')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Person')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': "RSVP's",
                'ordering': ('-created_at',),
            },
        ),
    ]
